name: My first CI

on:
  push:
    branches: [master]

jobs:
  build-on-ubuntu:
    runs-on: ubuntu-latest
    steps:

      - name: Step 1 - Checkout main branch from GitHub
        uses: actions/checkout@v2

      - name: Set up JDK 18
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 18

      - name: Step 3 - Build Maven Project
        run: mvn --batch-mode clean package -DskipTests


      - name: Step 4 - Run test cases
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test
